Required keywords for the Library Challenge
robocorp/rpaframework-msgraph pull request #5
Opened 2022-09-23 15:01 UTC by vinismarques

I believe I have completed all of the requirements, so here it is for your review.

I chose pytest instead of robot test because I could also use this opportunity to learn more about it.

Feedbacks are most welcome!

2022-09-23 17:48 UTC, blakewaud requested changes
Looks very good! Couple comments for you, one of which requires some more thought. I think we should support returning a Sharepoint list as an `RPA.Tables.Table` so it fits in with the rest of `rpaframework`.

2022-09-23 17:48 UTC, blakewaud commented on src/RPA/MSGraph.py
> +        return file.download(to_path=target_directory)
In our framework, it is more common to return a path to the downloaded file.

2022-09-23 17:48 UTC, blakewaud commented on src/RPA/MSGraph.py
> +        file = my_drive.get_item_by_path(file_path)
Rename this variable, no reason to shadow a builtin

2022-09-23 17:48 UTC, blakewaud commented on src/RPA/MSGraph.py
> +        file = my_drive.get_item_by_path(file_path)
Also, what if the user points to a folder here? Does a folder have a `download()` method as well or will the return throw an error?

2022-09-23 17:48 UTC, blakewaud commented on src/RPA/MSGraph.py
> +        """Returns a list of files found in OneDrive based on the search string.
Since we are using the `search()` method, I believe this will search any content shared with the user as well, so we should include that in the documentation so a user is not surprised.

2022-09-23 17:48 UTC, blakewaud commented on src/RPA/MSGraph.py
> +
There is no easy way to inspect attributes in Robot Framework, so we should enumerate the most important (if not all) of the available attributes when first introducing a new return object.

2022-09-23 17:48 UTC, blakewaud commented on src/RPA/MSGraph.py
> +        :return: SharePoint List found based on the provided list name.
How does a Robot Developer interact with this list? What does the return data look like? It could be very helpful to return this as an `RPA.Tables.Table`

2022-09-23 17:48 UTC, blakewaud commented on src/RPA/MSGraph.py
> +        file = sp_drive.get_item_by_path(file_path)
No need to shadow a built in here, you should rename.

2022-09-23 17:48 UTC, blakewaud commented on src/RPA/MSGraph.py
> +        If the drive_id is not informed, the defaul Document Library will be used.
Please fix typo

2022-09-23 18:18 UTC, vinismarques commented on src/RPA/MSGraph.py
> +                f"""Authentication not successful using
Good to know, thanks!

2022-09-23 18:29 UTC, vinismarques commented on src/RPA/MSGraph.py
> +                ${me}=    Get Me
I've been using the linter Robocop and it was pointing me towards this convention, so I assumed that this was it. I'll change it back. Thanks for letting me know!

2022-09-23 18:36 UTC, vinismarques commented on src/RPA/MSGraph.py
> +        file = sp_drive.get_item_by_path(file_path)
Do you mean that for the `file` variable? If yes, it doesn't appear to be a built-in.

2022-09-23 18:41 UTC, blakewaud commented on src/RPA/MSGraph.py
> +        file = sp_drive.get_item_by_path(file_path)
Yes, for `file`. Sonarlint indicates it shadows a builtin name.

2022-09-24 23:06 UTC, vinismarques commented on src/RPA/MSGraph.py
> +        file = my_drive.get_item_by_path(file_path)
As it is, it would throw an error. There is a method to download the contents of a folder, but it isn't the same as the one for files. I can implement it as well. Do you suggest creating a new keyword for that or do we rename the keywords with `Files` in the name to `Items` and make it `DriveItem` agnostic?

Example: 

- `List items in OneDrive folder` instead of `List files in OneDrive folder`
- `Download item from OneDrive` instead of `Download file from OneDrive`

2022-09-25 13:28 UTC, vinismarques commented on src/RPA/MSGraph.py
> +        :return: SharePoint List found based on the provided list name.
I think we are not currently using the library that provides `RPA.Tables`, so for now I changed the code to return it as a list of dictionaries, where each `ListItem` was converted into a dict. This new return can be very easily converted to `RPA.Tables.Table` by using the keyword `Create Table`. I added this as an example in the docstring as well.
With these changes in mind, do you think it is still worth returning a Table, or can we consider this resolved?

2022-09-26 20:38 UTC, blakewaud commented on src/RPA/MSGraph.py
> +        sp = self.client.sharepoint(resource=resource)
I am now testing this with a live version of SharePoint. Passing in a default of 'sites' to the resource causes the underlying app to construct the uri as `https://graph.microsoft.com/v1.0/sites/sites/beissi.sharepoint.com:/sites/test-site` with an extra `sites` in the path. When I deleted the `resources=resources` it worked. I think the default needs to be just the blank string like the underlying library uses as the default here.

2022-09-27 03:20 UTC, vinismarques commented on src/RPA/MSGraph.py
> +        :return: SharePoint List found based on the provided list name.
I changed the return to be a Table when the `RPA.Tables` library is available, similar to what is done in the [AWS lib](https://github.com/robocorp/rpaframework/blob/2b7499ce8180ce573bd502c9f19f508421b6550d/packages/aws/src/RPA/Cloud/AWS/__init__.py#L41) using optional imports.

I couldn't test it 100% because there is a package name conflict between `RPA.MSGraph` and `RPA.Tables`. Since you are testing it on a live SharePoint through Robot Framework it won't be an issue.

2022-09-27 03:23 UTC, vinismarques commented on src/RPA/MSGraph.py
> +        sp = self.client.sharepoint(resource=resource)
Thanks for catching this, it was fixed in commit https://github.com/robocorp/rpaframework-msgraph/pull/5/commits/a469e6f59480cd31906cac99f1af57a32a7339c0.

2022-09-27 16:07 UTC, blakewaud commented on src/RPA/MSGraph.py
> +        active_directory = self.client.directory(resource)
Testing live shows that the directory client cannot perform searches using the search parameter. You might have to use the `address_book` method which returns an `AddressBook` instance that has a method called `get_contacts`.

2022-09-27 17:56 UTC, blakewaud commented on src/RPA/MSGraph.py
> +        folder_path: str,
I think this should be made optional so if it is not provided, it would return the contents of the root of the user's default OneDrive.

2022-09-27 17:56 UTC, blakewaud commented on src/RPA/MSGraph.py
> +        folder_path: str,
I think this should be made optional so if it is not provided, it would return the contents of the root of the user's default OneDrive.

2022-09-27 18:11 UTC, blakewaud commented on src/RPA/MSGraph.py
> +        folder_path: str,
I see you actually need to use `get_root_folder` to get the root path. I suggest this change to the function... you may also want to consider giving the user an option to include folders so they can see what folders then can traverse down.

```python
    @keyword
    def list_files_in_onedrive_folder(
        self,
        folder_path: str = None,
        resource: Optional[str] = None,
        drive_id: Optional[str] = None,
    ) -> list[drive.DriveItem]:
        self._require_authentication()
        my_drive = self._get_drive_instance(resource, drive_id)
        if folder_path in [None,'/','\\','root','ROOT','']:
            folder = my_drive.get_root_folder()
        else:
            folder = my_drive.get_item_by_path(folder_path)
        items = folder.get_items()
        files = [item for item in items if not item.is_folder]
        return files
```

2022-09-27 18:45 UTC, blakewaud commented on src/RPA/MSGraph.py
> +        file_path: str,
Here's my implementation of it... the order of the Type hint matters for how Robot Framework auto converts the variable before calling the keyword.

```python
    @keyword
    def download_file_from_onedrive(
        self,
        file_path: Union[drive.File,str],
        target_directory: Optional[str] = None,
        resource: Optional[str] = None,
        drive_id: Optional[str] = None,
    ) -> bool:
        self._require_authentication()
        my_drive = self._get_drive_instance(resource, drive_id)
        if isinstance(file_path,str):
            file = my_drive.get_item_by_path(file_path)
        elif isinstance(file_path,drive.File):
            file = my_drive.get_item(file_path.object_id)
        return file.download(to_path=target_directory)
```

2022-09-27 18:56 UTC, blakewaud commented on src/RPA/MSGraph.py
> +        file_path: str,
You will need to implement the optional None becomes root path here as well.

2022-09-27 19:17 UTC, blakewaud commented on src/RPA/MSGraph.py
> +        file_path: str,
This needs to accept `DriveItem` as well, just like download from Onedrive

2022-09-27 20:14 UTC, blakewaud commented on src/RPA/MSGraph.py
> +            item_dict.update(item.fields)
In live testing, my `item.fields` is `None`. I am guessing you need to pass `expand_fields=True` via `get_items` before calling this function.

2022-09-27 20:23 UTC, blakewaud requested changes
Good changes so far. With the ability to test against a live Sharepoint site I found some other bugs that I've added as comments.

2022-09-27 20:23 UTC, blakewaud commented on src/RPA/MSGraph.py
> +
This function failed with error `Client Error: 404 Client Error: Not Found for url: https://graph.microsoft.com/v1.0/me/drive/items/01SC65K3X24DDZ3R2MXBHLVV5FK4GZCH4R/content | Error Message: The resource could not be found.`

This was given a share link shared within the same Sharepoint site between two users of that site. Not sure if you are constructing the encoded ID correctly in this instance, where did you get the documentation on that part?

2022-09-27 21:22 UTC, vinismarques commented on src/RPA/MSGraph.py
> +
Hmm, I'll look into it if this should work for SharePoint as well or only for shared OneDrive files. [Here](https://learn.microsoft.com/en-us/graph/api/shares-get?view=graph-rest-1.0&tabs=http) is the doc page about encoding URLs.

2022-09-28 01:43 UTC, vinismarques commented on src/RPA/MSGraph.py
> +        folder_path: str,
I added the behavior of defaulting to the root folder and I agree, having the option to also get folders is nice. For now, I added this feature as parameter `include_folders` which defaults to `False`, but I think there is room for improvement here. Maybe changing "files" keywords to "items" (more generic) or adding new keywords exclusively for folders (`Download Folder Contents` for example). See my comment in https://github.com/robocorp/rpaframework-msgraph/pull/5#discussion_r979328219.

2022-09-28 17:01 UTC, vinismarques commented on src/RPA/MSGraph.py
> +        folder_path: str,
Actually, this looks better than I thought. Maybe we only add the `Download Folder Contents` that require another method and call it a day.

2022-09-29 01:22 UTC, vinismarques commented on src/RPA/MSGraph.py
> +        active_directory = self.client.directory(resource)
If I understood correctly, the `AddressBook` can be used to work with contacts of the resource ("me", for example) or to work with the entire Active Directory, but when using Active Directory it returns a `Directory` all the same, so it's just there for backward compatibility (explained [here](https://github.com/O365/python-o365#the-global-address-list)).

I tried executing a simple example that is in the docs but it failed. There is something off in my personal Azure account, I get auth errors even when accessing the website. Seems like I can't use anything other than the "me" resource for now, so it is hard to troubleshoot this one.

Can you try to execute this example work? If that works for you, passing a query to `get_users` should work as well.

      directory = self.client.directory()
      for user in directory.get_users():
          print(user)

2022-09-29 15:39 UTC, blakewaud requested changes
Couple of small bugs from live testing to check out.

2022-09-29 15:39 UTC, blakewaud commented on src/RPA/MSGraph.py
> +        active_directory = self.client.directory(resource)
Sorry, I should have been more specific, I do believe the problem is that the Directory endpoint does not accept a `search` type of query, you can use `startswith`. I updated the function's code like below and it worked, so I am pretty sure it is the `search` that's breaking it:

```python
        self._require_authentication()
        active_directory = self.client.directory(resource)
        query = active_directory.new_query('display_name').startswith(search_string)
        return active_directory.get_users(query=query)
```

2022-10-04 16:51 UTC, blakewaud approved these changes
I was able to test successfully via robot against a live Sharepoint site!

2022-10-04 16:51 UTC, merged